import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="min-h-screen p-6 bg-gray-100">
          <header className="mb-6 flex justify-between items-center container mx-auto">
            <h1 className="text-2xl font-bold mb-4">AnnotatE</h1>
            <nav>
              <ul className="flex space-x-4">
                <li>
                  <Link href="/" className="text-blue-600 hover:underline">
                    Home
                  </Link>
                </li>
                <li>
                  <Link
                    href="/annotate"
                    className="text-blue-600 hover:underline"
                  >
                    Annotate
                  </Link>
                </li>
                <li>
                  <Link href="/about" className="text-blue-600 hover:underline">
                    About
                  </Link>
                </li>
              </ul>
            </nav>
          </header>

          <div className="container mx-auto">{children}</div>

          <footer className="mt-6 text-center text-gray-500">
            &copy; {new Date().getFullYear()} Your Company Name
          </footer>
        </main>
      </body>
    </html>
  );
}
